export const exifFields = [
  "ModifyDate",
  "Make",
  "Model",
  "AbsoluteAltitude",
  "RelativeAltitude",
  "GimbalRollDegree",
  "GimbalYawDegree",
  "GimbalPitchDegree",
  "FlightRollDegree",
  "FlightYawDegree",
  "FlightPitchDegree",
  "Orientation",
  "SerialNumber",
  "GPSAltitude",
  "GPSLatitudeRef",
  "GPSLongitudeRef",
  "GPSLongitude",
  "GPSLatitude",
  "latitude",
  "longitude",
  "CreateDate",
  "BrightnessValue",
  "FNumber",
  "ExposureTime",
  "ImageDescription",
];

export const imageExtensions = [".jpg", ".jpeg", ".png"];
